docs/AboutUs.md

I added my name to the aboutus file.

Add myself

---

docs/AboutUs.md

Jiqing about us

---

docs/AboutUs.md

Added Bryan Beh

---

src/main/java/seedu/duke/classes/Movie.java
src/main/java/seedu/duke/classes/Show.java

I think we should split shows and movie

Add Movie class

---

src/main/java/seedu/duke/classes/Movie.java
src/main/java/seedu/duke/utility/ErrorHandling.java
src/main/java/seedu/duke/utility/ShowList.java
src/main/java/seedu/duke/utility/Ui.java
src/test/java/seedu/duke/classes/ShowTest.java

Just add onto the Exceptions :)

Error class

---

src/main/java/seedu/duke/classes/Show.java
src/main/java/seedu/duke/commands/DeleteRatingCommand.java
src/main/java/seedu/duke/commands/RatingCommand.java
src/main/java/seedu/duke/utility/ShowList.java

Added Rating,changerating,deleterating command

Added Rating,ChangeRating,DeleteRating

---

src/main/java/seedu/duke/classes/Storage.java
src/main/java/seedu/duke/utility/SaveState.java

Added whitespaces for checkstylemain errors

Added Whitespaces for checkstylemain errors

---

src/main/java/seedu/duke/commands/UpdateShowEpisodeProgressCommand.java
src/main/java/seedu/duke/utility/InputParser.java

Fixed minor errors that appeared from merge conflict resolution

Error fixes

---

src/main/java/seedu/duke/commands/UpdateShowEpisodeProgressCommand.java
src/main/java/seedu/duke/commands/UpdateShowSeasonCommand.java
src/main/java/seedu/duke/utility/InputParser.java

Add some error handling examples for the track progress commands. Let me know if there's another way to do it thanks :)

Add error handling

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/classes/Movie.java
src/main/java/seedu/duke/classes/Show.java
src/main/java/seedu/duke/classes/Storage.java
src/main/java/seedu/duke/commands/UpdateShowEpisodeProgressCommand.java
src/main/java/seedu/duke/commands/UpdateShowSeasonCommand.java
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/SaveState.java
src/main/java/seedu/duke/utility/ShowList.java
src/main/java/seedu/duke/utility/Ui.java
src/test/java/seedu/duke/commands/UpdateShowEpisodeProgressCommandTest.java
src/test/java/seedu/duke/commands/UpdateShowSeasonCommandTest.java

toString function for Show.
Changed the inputparser list function portion.

Add showList function

---

src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/utility/ErrorHandling.java
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/Ui.java
src/test/java/seedu/duke/utility/InputParserTest.java

The add command works properly now, but error handling does not trigger when user inputs only 1 season (i.e add Showname 1 10,10)

Add InputParser tests and adjusted Add command error handling 

---

docs/UserGuide.md
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/StringOperations.java
src/main/java/seedu/duke/utility/Ui.java

Added Ui for watch time tracking. Also updated User Guide which hopefully can help our product pitch/demo fingers crossed

Update Ui and User Guide

---

src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/WatchCommand.java
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/SaveState.java
src/main/java/seedu/duke/utility/StringOperations.java
src/main/java/seedu/duke/utility/Ui.java

Added watch command which increments current episode by one.
However I'm not sure as to how we can track the current date using our watchtime class right now...

Add watch command

---

docs/UserGuide.md
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/classes/Show.java
src/main/java/seedu/duke/classes/WatchTime.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/EditCommand.java
src/main/java/seedu/duke/commands/WatchCommand.java

and show can be initialised with episode durations

Edit can now edit duration of episodes 

---

src/main/java/seedu/duke/classes/Show.java
src/main/java/seedu/duke/classes/WatchTime.java
src/main/java/seedu/duke/commands/EditCommand.java
src/main/java/seedu/duke/commands/UpdateTimeLimitCommand.java
src/main/java/seedu/duke/commands/WatchCommand.java
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/ShowList.java
src/main/java/seedu/duke/utility/Ui.java
src/test/java/seedu/duke/classes/StorageTest.java

FInished updatetimit command, added catch for edit command and other minor changes to get the correct output

FInish updatelimit command, add catch for edit show and minor changes

---

src/main/java/seedu/duke/commands/WatchCommand.java
src/main/java/seedu/duke/utility/Ui.java

This (should) fix the episode bounds checking issue. 
Also added additional UI prompts to update the user that he is now at a new season when he has finished his current season

Fixed episode bound check for Watch Command

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/duke/classes/Show.java
src/main/java/seedu/duke/commands/ChangeReviewCommand.java
src/main/java/seedu/duke/commands/DeleteReviewCommand.java
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/Ui.java

Added Commands to change review and also delete the review. Updated the DG implementation part.

Added new commands

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/duke/commands/AddReviewCommand.java
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/Ui.java

Updated the addreview command to allow rating to take in spaces. Used "/" to seperate rating from the review. Updated the UG and DG accordingly.

Allow rating to take in spaces

---

docs/DeveloperGuide.md
docs/UserGuide.md

Updated the details for implementation of edit command in UG and DG.

User Guide and Developer's Guide

---

src/main/java/seedu/duke/commands/SearchCommand.java
src/main/java/seedu/duke/utility/InputParser.java
src/main/java/seedu/duke/utility/Ui.java

Adjust search command to solve the PE-D issue on search inconsistency.,
Now search command prints out show details that contain the keyword, and is case insensitive as well.
We can change it back if you dont like it :(

Improved List command readability, commands case-insensitive, adjusted search command 
